### ISSUE TITLE
Virtual Panel Discussion

### ISSUE THREAD

**Issue by madjin** [open-metaverse-gathering/proposals#6]
Some folks want to have a panel discussion, so I figure we start a thread to discuss topics and logistics.

I propose we record in VRChat for higher production value in a virtual studio made by @gm3.

![podcast studio](https://i.imgur.com/1PAr60p.jpg)

We have room for 12 slides and a youtube video player in the virtual studio with seating for 5.

![light studio](https://i.imgur.com/4T2ywJ4.jpg)

Questions:

- What time?
- What topics do we want to discuss?
- Whose interested?

**Comment by RangerMauve** [comment]
Ooo can I rant about decentralization as part of this?

**Comment by avaer** [comment]
Conceptual thumbs up 👍. The only part I disagree with here is requiring people to install proprietary software (VRChat) to participate.

**Comment by madjin** [comment]
> Conceptual thumbs up 👍. The only part I disagree with here is requiring people to install proprietary software (VRChat) to participate.

I understand and just to let ya know there are plans to eventually migrate the system off VRChat to standalone unity, webgl export, or even a WebXR platform. If we're to discuss in stage 2 where we can change the background to blue/green screen then we could have a cameras record shots in a way that the archived footage can be replayed in any webvr scene.

This studio is completely ready to go and hasn't had much use. It's a great opportunity to learn about virtual production and discuss ideas in a higher quality avatar setting that can reach a wider audience.

**Comment by avaer** [comment]
@madjin do you guys have the code for the studio to share?

**Comment by gm3** [comment]
as our worlds merge I have question on porting my workflows into open source versions, as well as have some standalone versions to extend for my own productions. I have been researching cameras, and render textures, and I am interested in learning the specs on what is possible. The code we have is running on the VRC SDK

**Comment by gm3** [comment]
https://www.youtube.com/watch?v=G6gQ5dwBKe0 for reference here is some background on how we work

**Comment by smsithlord** [comment]
I'm interested.   I would want to talk about mixing real humans with web cams into virtual worlds, and also cross-broadcasting to promote synergy between communities rather than the classic battle for possession of users.

I like to put my IRL live web cam, chroma keyed, into an in-game virtual studio.  Here's a GIF of what I mean: https://gyazo.com/72ec554f9a905836410bdf5f25847cc0

Then, it's great to put other people's live streams on the studio wall screen there, and interact with each other live-from-location like they do on the TV news.

I think live-from-location interviews & interactions from other games would be great for promoting one another & showing that there's more stuff out there and that we all can get along & synergize instead of constantly competing for each other's users.  (A sense of "You guys use app X, and that is great!  Please share with us some of your favorite stuff from that universe and tell us why it's great for you.")

Below are a bunch more examples of the web-cam in-world thing for anybody interested.

Here I put my live web cam feed onto the face of my VR avatar, for some motion-ception:
https://gyazo.com/33f0b61da28c66549542a51394760584

Here I'm using my web cam in-world giving a presentation showing a hologram art gallery:
https://gyazo.com/7ec5bde338b8893feaeba0b8ea4c3800

Here's a video of a guy doing his web show from 1 world, with a viewing area in a different world:
https://twitter.com/anarchyarcade/status/1110925335938293762

And, while not related to the web cam stuff, gotta show a picture of the virtual infinity screen 🗡 https://gyazo.com/c0abbc2186cbbd2b29b36fe3416ff09f

**Comment by madjin** [comment]
Very cool! Would love to discuss either virtual production or virtual economy, I think perhaps the two may even be related. We should pick a time to have this event, think it will run separate from the usual M3 time. How does this Saturday sound? I'm thinking late night and recorded, not streamed.

**Comment by madjin** [comment]
Did some quick brainstorming with peeps on these two interesting topics: virtual productions and virtual economy

lets break it down...

virtual performance perhaps a good starting point
	- live events
	- stream broadcasts
	- conferences
	- ticket sales
	- actors as avatars instead of NPCs
	- voice actors

Education
        - borderless classrooms
	- karate or other physical training
	- meditation
	- foreign languages

Non-fungible tokens
	- tokenizing digital assets

Virtual Economy: What is the community worried about?
	- Vitalik and his WoW experience
	- Other virtual economy fails
	- Virtual Market
	- Virtual real estate

What's the stack?
	- Identity services
	- authentication

Act out a transaction in-world, ask panelists how it might work implementation wise.

There would be plenty to discuss in a 2 hour panel regarding these topics. Thoughts?

**Comment by madjin** [comment]
More planning and logistics updates!

There will be one rehearsal the day before we film the panel. **If you wanna be on the panel please be sure to attend rehearsal!**

During rehearsal we'll go over everything such as how the studio works, picking out an avatar for the show, answer any questions, etc. I'm thinking that will be this Friday.

Next, I think we'll aim to have 4 participants in the panel so that we can have enough time to cover questions and get peoples thoughts on each topic. 

However, I have an idea for how we can capture more voices via on-the-street style interviews:

![](https://i.imgur.com/GWNPSGj.jpg)

Kaban-chan has allowed an avatar with a shoulder camera and microphone prop to be cloneable (thank you!) which we can use to capture short interview clips any time to make a nice segment with.

If one preferred, we can do the same thing in [Hubs](https://hubs.mozilla.com) by spawning a camera/microphone prop also.

We came up with some ideas to name this production, haven't decided on anything yet:
- "Big Brain Talks"
- "The 🅱️etterverse"
- Still open to suggestions

**Comment by smsithlord** [comment]
I just noticed that that avatar has a live mirror attached to its shoulder.  It would be great if we could keep the mirrors, live streaming virtual screens, and other lag-inducing elements to only what's required for the recording, for performance reasons.  I do like the camera model being there for the psychological effect, but I fear the lag.  Just a suggestion.

**Comment by RangerMauve** [comment]
Regarding Friday's rehearsal, would it be okay to do it either earlier in the day or way late at night? I'm going to be yeeting out between 16:00 EDT and 22:00 EDT ish. 😅😅😅

**Comment by madjin** [comment]
> I just noticed that that avatar has a live mirror attached to its shoulder. It would be great if we could keep the mirrors, live streaming virtual screens, and other lag-inducing elements to only what's required for the recording, for performance reasons. I do like the camera model being there for the psychological effect, but I fear the lag. Just a suggestion.

The studio for the panel will not have such effects and the avatar will only be for 1:1 interviews which will be much less laggy. Also, the mirror effect only happens when you are friends with the person who is wearing the avatar.

> Regarding Friday's rehearsal, would it be okay to do it either earlier in the day or way late at night? I'm going to be yeeting out between 16:00 EDT and 22:00 EDT ish.

I've yet to nail down an exact time but when I do it'll be posted here. I think we can do early day or late night.

**Comment by gm3** [comment]
Sounds good, the "rehearsal" can be thought of more of a short meet and
greet where we can just pick some avatars, I can show you guys the studio,
and we can go over some of the format, so that we can get comfortable with
the room and production and crew, I say it would only be like 20 mins or
so/ Cheers!

**Comment by gm3** [comment]
Hey Guys How about 8pm Central to meet for quick 20 min meet and greet, I invited my friend Jeremy (who does some virtual events) and also my friend Artist3d, hopefully they can make it, but lets lock down a time, cheers!

**Comment by madjin** [comment]
One of the participants mentioned that the best time for them would be 4 hours later, around past 10pm pst. I'll double check with everyone else today.

**Comment by madjin** [comment]
We're going to meetup at 10pm pst tonight, expect to spend 20 minutes to troubleshoot any issues / change avatars / get prepared, then around 10:30pm we'll begin filming. Feel free to pick up an avatar you like anytime before, see you all then!

**Comment by madjin** [comment]
Thank you all for participating last night in the panel discussion, the recordings came out great and I have just finished processing the green screen video as well. There's a few items left for producers to wrap things up:

- [x] Edit the clips (intro/outro)
- [ ] Supercut street interviews
- [x] Timestamp interesting bits of recording
- [x] Write a description
- [x] Export studio model
- [x] Composite green screen clips into studio
- [ ] Finish dev log

Hopefully all will be completed by end of the week, cheers!
