### ISSUE TITLE
Blockchain Virtual Worlds Field Trip

### ISSUE THREAD

**Issue by madjin** [open-metaverse-gathering/proposals#9]
I propose that sometime after the launch of Decentraland and Somnium Space on Feb 20th we take a group field trip similar to the [Traversing Disparate Virtual Worlds](https://github.com/M3-org/research#traversing-disparate-virtual-worlds) event through [Cryptovoxels](https://www.cryptovoxels.com/), [Decentraland](https://decentraland.org/), and [Somnium Space](https://www.somniumspace.com/).

We can have meaningful discussions while exploring each app and record an epic video of our journey to accompany a research document. Post if interested in joining and if you have any questions that you think is worth discussing in each app!

**Comment by smsithlord** [comment]
I'll attend.  Opening day is one of the best days to explore social apps.  As for aspects to analyze in each app during a user field trip session on opening day, I think (1) how gracefully their servers handle the additional user load of their opening day event crowds, (2) whether or not the users seem to congregate in  common areas or all disperse into smaller groups and wonder off, (3) how entertaining the experience is for guests (like ourselves) who are not buying, investing, or building anything in the platform but merely there to enjoy it.

**Comment by avaer** [comment]
Not sure if opening day itself is the best time though. I know a few M3 people are going to be at various events on the 20th...

**Comment by AlanFalcon** [comment]
Love that idea

**Comment by jimmcnelis** [comment]
count me in!

**Comment by skyminelabs** [comment]
I'm in as well!

**Comment by madjin** [comment]
How does Thursday March 26th at 12pm PST sound for everyone?

**Comment by skyminelabs** [comment]
Works for me!  Can I invite a few others?

**Comment by madjin** [comment]
> Works for me! Can I invite a few others?

absolutely, I am thinking a bit later like 12:45pm - that cool?

**Comment by skyminelabs** [comment]
yeah

**Comment by smsithlord** [comment]
I'll be down to take a trip with y'all!

As for the opening week experience I obtained:
1. Their servers had lots of connectivity issues with me and my friends where I could see & hear them but they couldn't see or hear me.  We finally just gave up on playing together.
2. There were only a handful of users (mostly AFKers) around the spawn point, but after I wondered out of that area, I did not encounter even 1 other player.
3. There was basically no interaction beyond pressing static buttons - it did not feel game-like one bit.  There was a command you type into chat that would magically teleport you to a location flagged as having good high quality builds - and it did work - but everything was still of very similar art style and I got bored with exploring the ghost town within a couple hours.  (Also the graphics were extremely sub-par compared to AAA games.  Felt like a mobile or web app - which I know it was - but I had hopes it'd raise the bar.  Better graphics would have at least kept me exploring for longer.)

Positive points I noticed during the opening week experience were: (1) It ran in my web browser, which I appreciated, especially because I was wrestling with trying to get Somnium Space's desktop app to successfully update that day too.  (2) They fearlessly built 1 massive - sprawling - flat - sparsely populated 1-instance world comprised of a mosaic of non-AAA user-created plots with a very great amount of creative freedom.  This is something I always fantasized about as a player for many years - even if as an engineer the concept seemed to inherently require adjustment to be realistic.  Decentraland seems like they did not care.  They saw the dream, they reached for it.  Love it or hate it - Decentraland is an excellent illustration of these concepts deployed.

I haven't been back into Decentraland's corner of the metaverse in a couple weeks, so I'm looking forward to seeing how it's changed since launch.  And to explore the stuff with a group instead of getting stuck by my lonesome again.

**Comment by Brookhawk** [comment]
I should be in

**Comment by AlanFalcon** [comment]
@madjin has this moved to tomorrow or is it in 15 minutes?

**Comment by madjin** [comment]
Yeah good call, we're at the cent meetup in Cryptovoxels and there's an awesome art show right after so lets move this to tomorrow.

**Comment by almoravid** [comment]
I will happily meet you for this. So noon Pacific time Friday?

**Comment by madjin** [comment]
We will start gathering around 12:45pm PST and begin around 1pm PST on Friday, the meetup will last no longer than a couple hours. Also, remember to have Somnium Space installed (DL from the steam store and run it atleast once: https://store.steampowered.com/app/875480/Somnium_Space/).
Order will go from Decentraland -> Cryptovoxels -> Somnium Space
We'll jump on and coordinate in the Cryptovoxels discord voice channel when event starts.

**Comment by skyminelabs** [comment]
Is it correct that Somnium won't work on MacOS Catalina?

**Comment by madjin** [comment]
> Is it correct that Somnium won't work on MacOS Catalina?

I don't believe so

**Comment by skyminelabs** [comment]
Thanks Jin - that was cool!

**Comment by avaer** [comment]
👏
